name: banderablanca
description: Es tiempo de apoyarnos

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  freezed_annotation: ^0.7.1
  json_annotation: ^3.0.1
  connectivity: ^0.4.8+2
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  firebase_storage: ^3.1.5
  firebase_crashlytics: ^0.1.3+3
  # firebase_messaging: ^5.1.6
  image_picker: ^0.6.4
  camera: ^0.5.7+4
  package_info: ^0.4.0+16
  photo_view: ^0.9.2
  timeago: ^2.0.26
  font_awesome_flutter: ^8.5.0
  provider: ^4.0.4
  uuid: ^2.0.4
  intl: ^0.16.0
  email_validator: ^1.0.4
  google_maps_flutter: ^0.5.25+3
  geolocator: ^5.3.1
  google_maps_place_picker: ^0.9.2
  flutter_advanced_networkimage: ^0.7.0
  video_player: ^0.10.8+1
  mime: ^0.9.6+3
  video_thumbnail: ^0.2.0
  image: ^2.1.12
  path_provider: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  build_runner: ^1.8.1
  freezed: ^0.10.5
  json_serializable: ^3.3.0

dependency_overrides:
  image: 2.1.12

flutter:
  uses-material-design: true
  assets:
    - assets/icons/marker.png

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-Medium.ttf
    - family: Avenir Light
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-Light.ttf
    - family: Avenir Heavy
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-Heavy.ttf
    - family: Avenir Black
      fonts:
        - asset: assets/fonts/Avenir/AvenirLTStd-Black.ttf
        - weight: 900
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
    - family: Tajawal Light
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
    - family: Tajawal Bold
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
        - weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
